### PR TITLE
Fix source typos

### LINKED ISSUE #360: Source typos - checking if there is interest in a fix
I ran a code spellcheck and found that there were some typos in the source. Do you have any interest in a PR to fix these ?

```shell
$ codespell -q 3 -L indexin,kno,rightt,thist,uptodate
./src/app/GUI/canvaswindowevents.cpp:66: chaning ==> chaining, changing
./src/app/GUI/RenderWidgets/outputsettingsdialog.cpp:289: COMPLIENCE ==> COMPLIANCE
./src/app/GUI/RenderWidgets/outputsettingsdialog.cpp:306: COMPLIENCE ==> COMPLIANCE
./src/app/GUI/RenderWidgets/outputsettingsdialog.cpp:571: COMPLIENCE ==> COMPLIANCE
./src/app/GUI/RenderWidgets/outputsettingsdialog.cpp:576: COMPLIENCE ==> COMPLIANCE
./src/app/GUI/RenderWidgets/outputsettingsdialog.cpp:596: COMPLIENCE ==> COMPLIANCE
./src/app/GUI/RenderWidgets/outputsettingsdialog.cpp:601: COMPLIENCE ==> COMPLIANCE
./src/app/GUI/RenderWidgets/outputsettingsdialog.cpp:934: COMPLIENCE ==> COMPLIANCE
./src/app/GUI/RenderWidgets/outputsettingsdialog.cpp:939: COMPLIENCE ==> COMPLIANCE
./src/app/GUI/RenderWidgets/outputsettingsdialog.cpp:958: COMPLIENCE ==> COMPLIANCE
./src/app/GUI/RenderWidgets/outputsettingsdialog.h:43: COMPLIENCE ==> COMPLIANCE
./src/core/appsupport.cpp:484: preffered ==> preferred
./src/core/appsupport.cpp:490: preffered ==> preferred
./src/core/FileCacheHandlers/filehandlerobjref.cpp:3: hadler ==> handler
./src/core/FileCacheHandlers/filehandlerobjref.cpp:7: hadler ==> handler
./src/core/FileCacheHandlers/filehandlerobjref.h:33: hadler ==> handler
./src/core/FileCacheHandlers/filehandlerobjref.h:34: hadler ==> handler
./src/core/Animators/paintsettingsanimator.cpp:459: opactiy ==> opacity
./src/core/Animators/paintsettingsanimator.cpp:462: opactiy ==> opacity
./src/core/Animators/paintsettingsanimator.cpp:465: opactiy ==> opacity
./src/core/Animators/paintsettingsanimator.h:133: opactiy ==> opacity
./src/core/Animators/qrealanimator.cpp:58: intrface ==> interface
./src/core/Animators/qrealanimator.cpp:59: intrface ==> interface
./src/core/Animators/qrealanimator.cpp:65: intrface ==> interface
./src/core/Animators/qrealanimator.cpp:66: intrface ==> interface
./src/ui/widgets/glwindow.cpp:102: intrface ==> interface
./src/ui/widgets/glwindow.cpp:103: intrface ==> interface
./src/ui/widgets/glwindow.cpp:103: intrface ==> interface
./src/ui/widgets/glwindow.cpp:104: intrface ==> interface
./src/ui/widgets/performancesettingswidget.cpp:252: preffered ==> preferred
./src/ui/widgets/performancesettingswidget.cpp:254: preffered ==> preferred
./src/ui/widgets/performancesettingswidget.cpp:289: preffered ==> preferred
```

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -L indexin,kno,rightt,thist,uptodate`  
Closes #360

This PR is untested. Also there was hesitance for me around fixing the following typos (so I didn't).

https://github.com/search?q=repo%3Afriction2d%2Ffriction%20chaning&type=code
Is the word here, 'changing' ?

https://github.com/search?q=repo%3Afriction2d%2Ffriction%20preffered&type=code  
This should probably be 'preferred' but there are many instances of it and probably should be left alone.

### CODE REVIEW

File: src/core/Animators/qrealanimator.cpp [hunk 1]
```diff
@@ -55,15 +55,15 @@ void QrealAnimator::prp_setupTreeViewMenu(PropertyMenu * const menu) {
 
     const PropertyMenu::PlainSelectedOp<QrealAnimator> sOp =
     [](QrealAnimator * aTarget) {
-        const auto& intrface = DialogsInterface::instance();
-        intrface.showExpressionDialog(aTarget);
+        const auto& interface = DialogsInterface::instance();
```
Comment (rodlie) [inline src/core/Animators/qrealanimator.cpp:58]: Can't use `interface`, it's reserved in MSVC (Windows).

https://github.com/friction2d/friction/actions/runs/12444585488/job/34745004655

**Review by rodlie — CHANGES_REQUESTED** [review]

File: src/core/Animators/qrealanimator.cpp (hunk 1 above)
Comment (luzpaz) [reply src/core/Animators/qrealanimator.cpp:58]: Can you suggest an alternative that won't trigger a false positive typo ?

Comment (rodlie) [reply src/core/Animators/qrealanimator.cpp:58]: I usually use `iface`.

**Comment by rodlie** [comment]
> Is the word here, 'changing' ?

Yes.

> This should probably be 'preferred' but there are many instances of it and probably should be left alone.

Let's just keep it as-is for now.

**Comment by luzpaz** [comment]
>> Is the word here, 'changing' ?
> Yes

The it also looks like there is a typo in the function `showHideChildrenBeforeChaningPaintType()`[^1]

[^1]: https://github.com/search?q=repo%3Afriction2d%2Ffriction%20showHideChildrenBeforeChaningPaintType&type=code

**Comment by rodlie** [comment]
> > > Is the word here, 'changing' ?
> > > Yes
> 
> ITC, it also looks like there is a typo in the function `showHideChildrenBeforeChaningPaintType()`[1](#user-content-fn-1-d6f07c0d2c9b3f2aeef7b4f8eb34c295)


Yes, feel free to change https://github.com/search?q=repo%3Afriction2d%2Ffriction%20chaning&type=code

**Comment by luzpaz** [comment]
Done. Give me the green light and I'll squash and rebase

**Review by rodlie — APPROVED** [review]
